CREATE DATABASE bioproyect;

use bioproyect;

CREATE TABLE USUARIOS (
  USU_ID INT AUTO_INCREMENT PRIMARY KEY,
  USU_NOMBRE VARCHAR(40) NOT NULL,
  USU_CORREO VARCHAR(100) NOT NULL,
  USU_PASSWORD VARCHAR(50) NOT NULL,
  USU_IMGPERFIL VARCHAR(100)
);

CREATE TABLE PASSWORDS (
  PAS_ID INT AUTO_INCREMENT PRIMARY KEY,
  PAS_STATUS BIT NOT NULL,
  USU_ID INT NOT NULL,
  FOREIGN KEY (USU_ID) REFERENCES USUARIOS (USU_ID) 
); 

CREATE TABLE PUBLICACIONES (
  PUB_ID INT AUTO_INCREMENT PRIMARY KEY,
  PUB_NOMBRE VARCHAR(30) NOT NULL,
  PUB_PUBLICACION VARCHAR(100),
  PUB_COMENTARIO VARCHAR(1000),
  USU_ID INT NOT NULL,
  FOREIGN KEY (USU_ID) REFERENCES USUARIOS (USU_ID) 
);

     

CREATE TABLE LOGINS (
  LON_ID INT AUTO_INCREMENT PRIMARY KEY,
  USU_ID INT NOT NULL,
 FOREIGN KEY (USU_ID) REFERENCES USUARIOS (USU_ID) 
); 